### Spotify playlist; Feature selection and testing

In [1]:
import pandas as pd

In [17]:
df = pd.read_csv('df_audio_features.csv/df_audio_features.csv')

In [19]:
# dropping columns:
# --- > mode: doesn*t seem very usuful (only 2 different values)
# --- > key: doesn*t seem very usuful for categorizing (equal values doesn't match with equal genres)
# --- > speechiness: doesn*t seem very usuful for categorizing (equal values doesn't match with equal genres)
# --- > liveness: doesn*t seem very usuful for categorizing (equal values doesn't match with equal genres)
# --- > time_signature: doesn*t seem very usuful (only 2 different values)
# --- > duration_ms: doesn*t matter

In [22]:
df = df.drop(columns={'mode', 'key', 'speechiness', 'liveness', 'time_signature', 'duration_ms'})

In [24]:
df

,song_name,artist,danceability,energy,loudness,acousticness,instrumentalness,valence,tempo
0,My Band,D12,0.851,0.84900,-3.383,0.49700,0.000002,0.8440,120.014
1,The Real Slim Shady,Eminem,0.949,0.66100,-4.244,0.03020,0.000000,0.7600,104.504
2,Águas De Março,Antônio Carlos Jobim,0.642,0.33900,-15.503,0.85400,0.000000,0.4910,143.418
3,The Girl From Ipanema,Stan Getz,0.641,0.14000,-16.790,0.86700,0.001660,0.3880,129.318
4,"Paint It, Black",The Rolling Stones,0.464,0.79500,-9.267,0.04930,0.002440,0.6120,158.691
5,Sultans Of Swing,Dire Straits,0.733,0.79400,-10.023,0.06140,0.036700,0.9310,148.174
6,Space Raiders - Charlotte de Witte Remix,Eats Everything,0.749,0.73100,-10.865,0.00314,0.867000,0.0598,131.997
7,In Silence,Amelie Lens,0.736,0.84500,-12.017,0.00548,0.901000,0.1980,128.009
8,"Wiegenlied, Op. 49, No. 4 (Arr. for Cello and ...",Johannes Brahms,0.184,0.00833,-33.503,0.98900,0.596000,0.2110,61.541
9,Nocturne en mi bémol majeur opus 9 n°2: Ballad...,Frédéric Chopin,0.387,0.04510,-24.698,0.99000,0.913000,0.0710,61.494

In [58]:
def min_max_scaling(col):
    min_col = min(col)
    max_col = max(col)
    norm_val = []
    for val in col:
        norm_val.append((val - min_col) / (max_col - min_col))
    return norm_val

def range_scaling_0_1(col):
    min_col = 0
    max_col = 1
    norm_val = []
    for val in col:
        norm_val.append((val - min_col) / (max_col - min_col))
    return norm_val

def range_scaling_0_34(col):
    min_col = 0
    max_col = 34
    norm_val = []
    for val in col:
        norm_val.append((- val - min_col) / (max_col - min_col))
    return norm_val

# no range scaling for tempo; max and min values...

In [35]:
df_scale = df.drop(columns={'song_name', 'artist'})

In [38]:
column_list=[]
for column in df_scale.columns:
    column_list.append(column)
column_list

['danceability',
 'energy',
 'loudness',
 'acousticness',
 'instrumentalness',
 'valence',
 'tempo']

In [64]:
df_scale.apply(min_max_scaling)

,danceability,energy,loudness,acousticness,instrumentalness,valence,tempo
0,0.871895,1.000000,1.000000,0.500436,0.000002,0.900138,0.602076
1,1.000000,0.776369,0.971414,0.027420,0.000000,0.803719,0.442503
2,0.598693,0.393341,0.597610,0.862189,0.000000,0.494949,0.842866
3,0.597386,0.156625,0.554880,0.875362,0.001818,0.376722,0.697799
4,0.366013,0.935766,0.804648,0.046775,0.002673,0.633838,1.000000
5,0.717647,0.934576,0.779548,0.059036,0.040197,1.000000,0.891797
6,0.738562,0.859636,0.751594,0.000000,0.949617,0.000000,0.725362
7,0.721569,0.995242,0.713347,0.002371,0.986857,0.158632,0.684332
8,0.000000,0.000000,0.000000,0.998987,0.652793,0.173554,0.000484
9,0.265359,0.043739,0.292331,1.000000,1.000000,0.012856,0.000000

In [62]:
df_scale.drop(columns={'loudness', 'tempo'}).apply(range_scaling_0_1)

   danceability   energy  acousticness  instrumentalness  valence
0         0.851  0.84900       0.49700          0.000002   0.8440
1         0.949  0.66100       0.03020          0.000000   0.7600
2         0.642  0.33900       0.85400          0.000000   0.4910
3         0.641  0.14000       0.86700          0.001660   0.3880
4         0.464  0.79500       0.04930          0.002440   0.6120
5         0.733  0.79400       0.06140          0.036700   0.9310
6         0.749  0.73100       0.00314          0.867000   0.0598
7         0.736  0.84500       0.00548          0.901000   0.1980
8         0.184  0.00833       0.98900          0.596000   0.2110
9         0.387  0.04510       0.99000          0.913000   0.0710

In [63]:
df_scale.filter(['index', 'loudness']).apply(range_scaling_0_34)

   loudness
0  0.099500
1  0.124824
2  0.455971
3  0.493824
4  0.272559
5  0.294794
6  0.319559
7  0.353441
8  0.985382
9  0.726412